language: c
before_install:
    - wget https://github.com/libcheck/check/files/71408/check-0.10.0.tar.gz
    - tar -xvf check-0.10.0.tar.gz
    - cd check-0.10.0
    - ./configure
    - make
    - sudo make install
    #- export CPATH=$(pwd)/src:$CPATH
    #- export LD_LIBRARY_PATH=$(pwd)/src/.libs:$LD_LIBRARY_PATH
    - export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
    - cd ..
